config/routes.rb
AddressBook::Application.routes.draw do
  resources :cities

  resources :people

  

end

app/models/city.rb
class City < ActiveRecord::Base

  #Elevation Validation
  validates :elevation,
            :numericality => {
                :greater_than_or_equal_to => 3315,
                :if => lambda {|city| city.state == "CO"},
                :message => "is too low, lowest point  in CO is 3315 feet."
            }

  #Population Validation
  validates :population,
            :numericality => {
                :greater_than => 0
            }

  #No Blank Fields Validation
  validates :name,
            :population,
            :elevation,
            :state,
            :presence =>  true

  #
  validates :name, format: { with: /\A[a-zA-Z]+\z/,
      message: "Only letters allowed" }


  #State Abbreviation Validation
  @us_states = [
      "AK","Alaska",
      "AL","Alabama",
      "AR","Arkansas",
      "AZ","Arizona",
      "CA","California",
      "CO","Colorado",
      "CT","Connecticut",
      "DC","District of Columbia",
      "DE","Delaware",
      "FL","Florida",
      "GA","Georgia",
      "HI","Hawaii",
      "IA","Iowa",
      "ID","Idaho",
      "IL","Illinois",
      "IN","Indiana",
      "KS","Kansas",
      "KY","Kentucky",
      "LA","Louisiana",
      "MA","Massachusetts",
      "MD","Maryland",
      "ME","Maine",
      "MI","Michigan",
      "MN","Minnesota",
      "MO","Missouri",
      "MS","Mississippi",
      "MT","Montana",
      "NC","North Carolina",
      "ND","North Dakota",
      "NE","Nebraska",
      "NH","New Hampshire",
      "NJ","New Jersey",
      "NM","New Mexico",
      "NV","Nevada",
      "NY","New York",
      "OH","Ohio",
      "OK","Oklahoma",
      "OR","Oregon",
      "PA","Pennsylvania",
      "RI","Rhode Island",
      "SC","South Carolina",
      "SD","South Dakota",
      "TN","Tennessee",
      "TX","Texas",
      "UT","Utah",
      "VA","Virginia",
      "VI","Virgin Islands",
      "VT","Vermont",
      "WA","Washington",
      "WI","Wisconsin",
      "WV","West Virginia",
      "WY","Wyoming" ]

  validates :state, :inclusion => { :in => @us_states }

end

app/models/person.rb
class Person < ActiveRecord::Base

  #No Blank Fields Validation
  validates :first_name,
            :last_name,
            :email,
            :address_line_one,
            :city,
            :state,
            :zip_code,
            :presence => true

  #State Abbreviation Validation
  @us_states = [
      "AK","Alaska",
      "AL","Alabama",
      "AR","Arkansas",
      "AZ","Arizona",
      "CA","California",
      "CO","Colorado",
      "CT","Connecticut",
      "DC","District of Columbia",
      "DE","Delaware",
      "FL","Florida",
      "GA","Georgia",
      "HI","Hawaii",
      "IA","Iowa",
      "ID","Idaho",
      "IL","Illinois",
      "IN","Indiana",
      "KS","Kansas",
      "KY","Kentucky",
      "LA","Louisiana",
      "MA","Massachusetts",
      "MD","Maryland",
      "ME","Maine",
      "MI","Michigan",
      "MN","Minnesota",
      "MO","Missouri",
      "MS","Mississippi",
      "MT","Montana",
      "NC","North Carolina",
      "ND","North Dakota",
      "NE","Nebraska",
      "NH","New Hampshire",
      "NJ","New Jersey",
      "NM","New Mexico",
      "NV","Nevada",
      "NY","New York",
      "OH","Ohio",
      "OK","Oklahoma",
      "OR","Oregon",
      "PA","Pennsylvania",
      "RI","Rhode Island",
      "SC","South Carolina",
      "SD","South Dakota",
      "TN","Tennessee",
      "TX","Texas",
      "UT","Utah",
      "VA","Virginia",
      "VI","Virgin Islands",
      "VT","Vermont",
      "WA","Washington",
      "WI","Wisconsin",
      "WV","West Virginia",
      "WY","Wyoming" ]

  validates :state, :inclusion => { :in => @us_states }

  #Zip_code Validation
  validates :zip_code, length: { minimum: 5 }


  #Email Format
  validates :email,
            uniqueness: true

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                             message: "Format Required: person@example.com" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :population, :elevation, :state)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.order(:last_name).all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :address_line_one, :city, :state, :zip_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.text_field :population %>
  </div>
  <div class="field">
    <%= f.label :elevation %><br>
    <%= f.text_field :elevation %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Population</th>
      <th>Elevation</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.population %></td>
        <td><%= city.elevation %></td>
        <td><%= city.state %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Population:</strong>
  <%= @city.population %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @city.elevation %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address_line_one %><br>
    <%= f.text_field :address_line_one %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr class=<%= cycle("even", "odd") %>>
        <td><%= person.last_name %></td>
        <td><%= person.first_name %></td>
        <td>
          <%= person.address_line_one %><br/>
          <%= person.city %>, <%= person.state %>, <%= person.zip_code %>
        </td>
        <td><%= mail_to person.email %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Address line one:</strong>
  <%= @person.address_line_one %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @person.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @person.zip_code %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>